### ISSUE TITLE
Paired reads

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [pratas/falcon#7]
It is not clear from the documentation how FALCON handles paired reads. Can you clarify please.
Thanks.

**Comment by pratas** [comment]
It does. The files: [FILE1]:[FILE2] stand for each one. It also allows to use multiple files from different paired ends. For example F1 and R1 with F2 and R2: ./FALCON <parameters> F1.fq:R1.fq:F2.fq:R2.fq.
I will add information for this in the README.am
