### ISSUE TITLE
Explanation of options

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [pratas/falcon#8]
Hi,
can you please provide explanations of what the following options do, i.e. their expected effect of outputs and speed / accuracy etc. I cannot find any explanation in the documentation or in the cited paper.

FALCON:
-Z
-l
-p
-t

FALCON-filter
-s
-w
-x
-sl
-su
-dl
-t

Thanks very much.

**Comment by pratas** [comment]
Its here: https://www.biorxiv.org/content/biorxiv/suppl/2018/02/27/267179.DC1/267179-1.pdf

**Comment by theo-allnutt-bioinformatics** [comment]
It would be a good idea to link to that in the readme.

Thanks.

**Comment by theo-allnutt-bioinformatics** [comment]
N.B. That supplementary note has a differently namedprogram: "FALCON-EYE".

I still cannot see any explanation of -Z, -l, -p, -t. Only for -c.

FALCON-FILTER options, again, are not explained.

When running FALCON on e.g. 100 metagenomic files, putting the file paths into the command line is not very practicable. Is there a way to use a file list file instead? Normally, I would make a wrapper to loop through the files, but the compression stage for the analysis would have to be repeated for each one.

Thanks.

**Comment by theo-allnutt-bioinformatics** [comment]
I think perhaps, I have missed the point of FALCON. I was trying to use it to obtain an estimate of abundance of each taxon identified, but now that I see my first output, I do not think it gives this information, or is it meant to analyse a mixture of metagenomes.. you are using it to identify a single genome?

**Comment by pratas** [comment]
It was linked. The documentation needs some update since the third version changed the names.

**Comment by pratas** [comment]
The objective is to identify the most representative genomes in a set of FASTQ reads. The % values indicate how much a reference is represented (in similarity) relative to the reads. For using for than one name, excluding the option to put all the names in command line, you may concatenate the reads since the internal models will efficiently deal with all.

**Comment by pratas** [comment]
Falcon also takes into account SNPs and other polymorphisms. Therefore, the similarity value will take that into account.

**Comment by pratas** [comment]
-Z                       database local similarity,    -> This allows to run local similarity, which is fundamental when sequences from database have duplicates or artifacts. If you are interested only in the top file of the most representative sequences, this does not need to be used. 
         
  -l <level>               compression level [1;47],    -> The technology of similarity estimation is based on relative compression. Better (optimized) models provide better compression and hence accurate estimations. However, computational resources are a problem. This option enables to balance RAM and time with precision. To see the levels, run -s (this will show different setups with cooperations of Markov models and tolerant Markov models).        
       
  -p <sample>              subsampling (default: 1) -> if it runs base by base or two in two bases, etc. This enables to run in a portion of the FASTQ files only.           
[top2.pdf](https://github.com/cobilab/falcon/files/3647244/top2.pdf)
       
  -t <top>                 top of similarity (default: 20) -> this is keeps only the best t matches. In the end of FALCON run you will have a top with the most representative sequences (see the image with an example).
